import SwiftUI

/// The small theme layer over the asset catalog. Every colour lives in
/// `Resources/Assets.xcassets/Palette` (Any / Dark / High Contrast variants,
/// regenerated by `scripts/generate_palette.py`), and is read as
/// `Color(.ink)` through the generated `ColorResource` symbols.
///
/// Only the roles that change with app state live here: crisis mode swaps the
/// brand tint for the sober `crisis-tint` everywhere and drops the art.
nonisolated struct Theme: Hashable, Sendable {
    var isCrisis = false

    // The generated ColorResource symbols are main-actor isolated.

    /// Actions, links and selection.
    @MainActor var accent: Color { Color(isCrisis ? .crisisTint : .tint) }
    /// The one filled button per view.
    @MainActor var accentFill: Color { Color(isCrisis ? .crisisTint : .tintFill) }
    /// Label and symbol on `accentFill`.
    @MainActor var onAccentFill: Color { Color(isCrisis ? .onCrisisTint : .onTint) }
}

extension EnvironmentValues {
    @Entry var theme = Theme()
}
